version: 2
updates:
- package-ecosystem: nuget
  directory: "/eFormAPI/eFormAPI.Web.Integration.Tests"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/eFormAPI/eFormAPI.Web.Tests"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/eFormAPI/eFormAPI.Web"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/eform-client"
  schedule:
    interval: daily